// AUTO-GENERATED — do not edit by hand.
// Source: NBA.com official schedule (cdn.nba.com scheduleLeagueV2, season 2026-27).
// Regenerate with: node scripts/gen-games.cjs
// Generated: 2026-10-04T03:27:28.117Z
// Range: 2026-10-20 .. 2026-11-01 (Weeks 1-2 of the 2026-27 regular season)
import { Game } from "./types";

export const GAMES: Game[] = [
  {
    id: "celtics-at-pistons-2026-10-20",
    gameId: "0022600001",
    gameCode: "20261020/BOSDET",
    homeTeamSlug: "pistons",
    awayTeamSlug: "celtics",
    date: "2026-10-20T19:00:00Z",
    status: "scheduled",
    arena: "Little Caesars Arena",
    arenaCity: "Detroit",
    arenaState: "MI",
    broadcast: "NBC / Peacock",
    nationalTv: ["NBC","Peacock"],
    nationalOtt: [],
    homeTv: [],
    awayTv: [],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 1",
  },
  {
    id: "76ers-at-knicks-2026-10-20",
    gameId: "0022600002",
    gameCode: "20261020/PHINYK",
    homeTeamSlug: "knicks",
    awayTeamSlug: "76ers",
    date: "2026-10-20T23:00:00Z",
    status: "scheduled",
    arena: "Madison Square Garden",
    arenaCity: "New York",
    arenaState: "NY",
    broadcast: "NBC / Peacock",
    nationalTv: ["NBC","Peacock"],
    nationalOtt: [],
    homeTv: [],
    awayTv: [],
    radio: ["ESPN Radio","SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 1",
  },
  {
    id: "thunder-at-spurs-2026-10-21",
    gameId: "0022600003",
    gameCode: "20261020/OKCSAS",
    homeTeamSlug: "spurs",
    awayTeamSlug: "thunder",
    date: "2026-10-21T01:30:00Z",
    status: "scheduled",
    arena: "Frost Bank Center",
    arenaCity: "San Antonio",
    arenaState: "TX",
    broadcast: "NBC / Peacock",
    nationalTv: ["NBC","Peacock"],
    nationalOtt: [],
    homeTv: [],
    awayTv: [],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 1",
  },
  {
    id: "hawks-at-magic-2026-10-21",
    gameId: "0022600085",
    gameCode: "20261021/ATLORL",
    homeTeamSlug: "magic",
    awayTeamSlug: "hawks",
    date: "2026-10-21T23:00:00Z",
    status: "scheduled",
    arena: "Kia Center",
    arenaCity: "Orlando",
    arenaState: "FL",
    broadcast: "NBA League Pass",
    nationalTv: [],
    nationalOtt: [],
    homeTv: [],
    awayTv: [],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 1",
  },
  {
    id: "bucks-at-wizards-2026-10-21",
    gameId: "0022600086",
    gameCode: "20261021/MILWAS",
    homeTeamSlug: "wizards",
    awayTeamSlug: "bucks",
    date: "2026-10-21T23:00:00Z",
    status: "scheduled",
    arena: "Capital One Arena",
    arenaCity: "Washington",
    arenaState: "DC",
    broadcast: "NBA League Pass",
    nationalTv: [],
    nationalOtt: [],
    homeTv: [],
    awayTv: [],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 1",
  },
  {
    id: "timberwolves-at-heat-2026-10-21",
    gameId: "0022600004",
    gameCode: "20261021/MINMIA",
    homeTeamSlug: "heat",
    awayTeamSlug: "timberwolves",
    date: "2026-10-21T23:30:00Z",
    status: "scheduled",
    arena: "Kaseya Center",
    arenaCity: "Miami",
    arenaState: "FL",
    broadcast: "ESPN",
    nationalTv: ["ESPN"],
    nationalOtt: [],
    homeTv: [],
    awayTv: [],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 1",
  },
  {
    id: "hornets-at-nets-2026-10-21",
    gameId: "0022600087",
    gameCode: "20261021/CHABKN",
    homeTeamSlug: "nets",
    awayTeamSlug: "hornets",
    date: "2026-10-21T23:30:00Z",
    status: "scheduled",
    arena: "Barclays Center",
    arenaCity: "Brooklyn",
    arenaState: "NY",
    broadcast: "NBA League Pass",
    nationalTv: [],
    nationalOtt: [],
    homeTv: ["DAZN (YES)"],
    awayTv: [],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 1",
  },
  {
    id: "bulls-at-raptors-2026-10-21",
    gameId: "0022600088",
    gameCode: "20261021/CHITOR",
    homeTeamSlug: "raptors",
    awayTeamSlug: "bulls",
    date: "2026-10-21T23:30:00Z",
    status: "scheduled",
    arena: "Scotiabank Arena",
    arenaCity: "Toronto",
    arenaState: "ON",
    broadcast: "NBA League Pass",
    nationalTv: [],
    nationalOtt: [],
    homeTv: [],
    awayTv: ["Chicago Sports Network"],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 1",
  },
  {
    id: "jazz-at-grizzlies-2026-10-22",
    gameId: "0022600089",
    gameCode: "20261021/UTAMEM",
    homeTeamSlug: "grizzlies",
    awayTeamSlug: "jazz",
    date: "2026-10-22T00:00:00Z",
    status: "scheduled",
    arena: "FedExForum",
    arenaCity: "Memphis",
    arenaState: "TN",
    broadcast: "NBA League Pass",
    nationalTv: [],
    nationalOtt: [],
    homeTv: [],
    awayTv: [],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 1",
  },
  {
    id: "pacers-at-pelicans-2026-10-22",
    gameId: "0022600090",
    gameCode: "20261021/INDNOP",
    homeTeamSlug: "pelicans",
    awayTeamSlug: "pacers",
    date: "2026-10-22T00:00:00Z",
    status: "scheduled",
    arena: "Smoothie King Center",
    arenaCity: "New Orleans",
    arenaState: "LA",
    broadcast: "NBA League Pass",
    nationalTv: [],
    nationalOtt: [],
    homeTv: [],
    awayTv: [],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 1",
  },
  {
    id: "mavericks-at-rockets-2026-10-22",
    gameId: "0022600091",
    gameCode: "20261021/DALHOU",
    homeTeamSlug: "rockets",
    awayTeamSlug: "mavericks",
    date: "2026-10-22T00:30:00Z",
    status: "scheduled",
    arena: "Toyota Center",
    arenaCity: "Houston",
    arenaState: "TX",
    broadcast: "NBA League Pass",
    nationalTv: [],
    nationalOtt: [],
    homeTv: [],
    awayTv: [],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 1",
  },
  {
    id: "warriors-at-lakers-2026-10-22",
    gameId: "0022600005",
    gameCode: "20261021/GSWLAL",
    homeTeamSlug: "lakers",
    awayTeamSlug: "warriors",
    date: "2026-10-22T02:00:00Z",
    status: "scheduled",
    arena: "Crypto.com Arena",
    arenaCity: "Los Angeles",
    arenaState: "CA",
    broadcast: "ESPN",
    nationalTv: ["ESPN"],
    nationalOtt: [],
    homeTv: [],
    awayTv: [],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 1",
  },
  {
    id: "suns-at-blazers-2026-10-22",
    gameId: "0022600092",
    gameCode: "20261021/PHXPOR",
    homeTeamSlug: "blazers",
    awayTeamSlug: "suns",
    date: "2026-10-22T02:00:00Z",
    status: "scheduled",
    arena: "Moda Center",
    arenaCity: "Portland",
    arenaState: "OR",
    broadcast: "NBA League Pass",
    nationalTv: [],
    nationalOtt: [],
    homeTv: ["KUNP"],
    awayTv: ["KTVK/KPHE/AZFS App"],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 1",
  },
  {
    id: "kings-at-clippers-2026-10-22",
    gameId: "0022600093",
    gameCode: "20261021/SACLAC",
    homeTeamSlug: "clippers",
    awayTeamSlug: "kings",
    date: "2026-10-22T02:30:00Z",
    status: "scheduled",
    arena: "Intuit Dome",
    arenaCity: "Inglewood",
    arenaState: "CA",
    broadcast: "NBA League Pass",
    nationalTv: [],
    nationalOtt: [],
    homeTv: [],
    awayTv: ["NBCSCA"],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 1",
  },
  {
    id: "cavaliers-at-76ers-2026-10-22",
    gameId: "0022600006",
    gameCode: "20261022/CLEPHI",
    homeTeamSlug: "76ers",
    awayTeamSlug: "cavaliers",
    date: "2026-10-22T23:00:00Z",
    status: "scheduled",
    arena: "Xfinity Mobile Arena",
    arenaCity: "Philadelphia",
    arenaState: "PA",
    broadcast: "ESPN",
    nationalTv: ["ESPN"],
    nationalOtt: [],
    homeTv: [],
    awayTv: [],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 1",
  },
  {
    id: "nuggets-at-thunder-2026-10-23",
    gameId: "0022600007",
    gameCode: "20261022/DENOKC",
    homeTeamSlug: "thunder",
    awayTeamSlug: "nuggets",
    date: "2026-10-23T01:30:00Z",
    status: "scheduled",
    arena: "Paycom Center",
    arenaCity: "Oklahoma City",
    arenaState: "OK",
    broadcast: "ESPN",
    nationalTv: ["ESPN"],
    nationalOtt: [],
    homeTv: [],
    awayTv: [],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 1",
  },
  {
    id: "knicks-at-celtics-2026-10-23",
    gameId: "0022600008",
    gameCode: "20261023/NYKBOS",
    homeTeamSlug: "celtics",
    awayTeamSlug: "knicks",
    date: "2026-10-23T23:00:00Z",
    status: "scheduled",
    arena: "TD Garden",
    arenaCity: "Boston",
    arenaState: "MA",
    broadcast: "Prime Video",
    nationalTv: ["Prime Video"],
    nationalOtt: [],
    homeTv: [],
    awayTv: [],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 1",
  },
  {
    id: "hawks-at-hornets-2026-10-23",
    gameId: "0022600094",
    gameCode: "20261023/ATLCHA",
    homeTeamSlug: "hornets",
    awayTeamSlug: "hawks",
    date: "2026-10-23T23:00:00Z",
    status: "scheduled",
    arena: "Spectrum Center",
    arenaCity: "Charlotte",
    arenaState: "NC",
    broadcast: "NBA League Pass",
    nationalTv: [],
    nationalOtt: [],
    homeTv: [],
    awayTv: [],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 1",
  },
  {
    id: "mavericks-at-pacers-2026-10-23",
    gameId: "0022600095",
    gameCode: "20261023/DALIND",
    homeTeamSlug: "pacers",
    awayTeamSlug: "mavericks",
    date: "2026-10-23T23:00:00Z",
    status: "scheduled",
    arena: "Gainbridge Fieldhouse",
    arenaCity: "Indianapolis",
    arenaState: "IN",
    broadcast: "NBA League Pass",
    nationalTv: [],
    nationalOtt: [],
    homeTv: [],
    awayTv: [],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 1",
  },
  {
    id: "timberwolves-at-magic-2026-10-23",
    gameId: "0022600096",
    gameCode: "20261023/MINORL",
    homeTeamSlug: "magic",
    awayTeamSlug: "timberwolves",
    date: "2026-10-23T23:00:00Z",
    status: "scheduled",
    arena: "Kia Center",
    arenaCity: "Orlando",
    arenaState: "FL",
    broadcast: "NBA League Pass",
    nationalTv: [],
    nationalOtt: [],
    homeTv: [],
    awayTv: [],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 1",
  },
  {
    id: "raptors-at-wizards-2026-10-23",
    gameId: "0022600097",
    gameCode: "20261023/TORWAS",
    homeTeamSlug: "wizards",
    awayTeamSlug: "raptors",
    date: "2026-10-23T23:00:00Z",
    status: "scheduled",
    arena: "Capital One Arena",
    arenaCity: "Washington",
    arenaState: "DC",
    broadcast: "NBA League Pass",
    nationalTv: [],
    nationalOtt: [],
    homeTv: [],
    awayTv: [],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 1",
  },
  {
    id: "pistons-at-heat-2026-10-24",
    gameId: "0022600098",
    gameCode: "20261023/DETMIA",
    homeTeamSlug: "heat",
    awayTeamSlug: "pistons",
    date: "2026-10-24T00:00:00Z",
    status: "scheduled",
    arena: "Kaseya Center",
    arenaCity: "Miami",
    arenaState: "FL",
    broadcast: "NBA League Pass",
    nationalTv: [],
    nationalOtt: [],
    homeTv: ["WPLG Local 10"],
    awayTv: [],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 1",
  },
  {
    id: "bulls-at-bucks-2026-10-24",
    gameId: "0022600099",
    gameCode: "20261023/CHIMIL",
    homeTeamSlug: "bucks",
    awayTeamSlug: "bulls",
    date: "2026-10-24T00:00:00Z",
    status: "scheduled",
    arena: "Fiserv Forum",
    arenaCity: "Milwaukee",
    arenaState: "WI",
    broadcast: "NBA League Pass",
    nationalTv: [],
    nationalOtt: [],
    homeTv: [],
    awayTv: ["Chicago Sports Network Plus"],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 1",
  },
  {
    id: "rockets-at-spurs-2026-10-24",
    gameId: "0022600009",
    gameCode: "20261023/HOUSAS",
    homeTeamSlug: "spurs",
    awayTeamSlug: "rockets",
    date: "2026-10-24T01:30:00Z",
    status: "scheduled",
    arena: "Moody Center",
    arenaCity: "Austin",
    arenaState: "TX",
    broadcast: "Prime Video",
    nationalTv: ["Prime Video"],
    nationalOtt: [],
    homeTv: [],
    awayTv: [],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 1",
  },
  {
    id: "pelicans-at-jazz-2026-10-24",
    gameId: "0022600100",
    gameCode: "20261023/NOPUTA",
    homeTeamSlug: "jazz",
    awayTeamSlug: "pelicans",
    date: "2026-10-24T01:30:00Z",
    status: "scheduled",
    arena: "Delta Center",
    arenaCity: "Salt Lake City",
    arenaState: "UT",
    broadcast: "NBA League Pass",
    nationalTv: [],
    nationalOtt: [],
    homeTv: [],
    awayTv: [],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 1",
  },
  {
    id: "grizzlies-at-warriors-2026-10-24",
    gameId: "0022600101",
    gameCode: "20261023/MEMGSW",
    homeTeamSlug: "warriors",
    awayTeamSlug: "grizzlies",
    date: "2026-10-24T02:00:00Z",
    status: "scheduled",
    arena: "Chase Center",
    arenaCity: "San Francisco",
    arenaState: "CA",
    broadcast: "NBA League Pass",
    nationalTv: [],
    nationalOtt: [],
    homeTv: ["NBCSBA"],
    awayTv: [],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 1",
  },
  {
    id: "clippers-at-lakers-2026-10-24",
    gameId: "0022600102",
    gameCode: "20261023/LACLAL",
    homeTeamSlug: "lakers",
    awayTeamSlug: "clippers",
    date: "2026-10-24T02:00:00Z",
    status: "scheduled",
    arena: "Crypto.com Arena",
    arenaCity: "Los Angeles",
    arenaState: "CA",
    broadcast: "NBA League Pass",
    nationalTv: [],
    nationalOtt: [],
    homeTv: ["Spectrum SportsNet"],
    awayTv: [],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 1",
  },
  {
    id: "blazers-at-kings-2026-10-24",
    gameId: "0022600103",
    gameCode: "20261023/PORSAC",
    homeTeamSlug: "kings",
    awayTeamSlug: "blazers",
    date: "2026-10-24T02:00:00Z",
    status: "scheduled",
    arena: "Golden 1 Center",
    arenaCity: "Sacramento",
    arenaState: "CA",
    broadcast: "NBA League Pass",
    nationalTv: [],
    nationalOtt: [],
    homeTv: ["NBCSCA"],
    awayTv: ["KUNP"],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 1",
  },
  {
    id: "heat-at-hornets-2026-10-24",
    gameId: "0022600104",
    gameCode: "20261024/MIACHA",
    homeTeamSlug: "hornets",
    awayTeamSlug: "heat",
    date: "2026-10-24T22:00:00Z",
    status: "scheduled",
    arena: "Spectrum Center",
    arenaCity: "Charlotte",
    arenaState: "NC",
    broadcast: "NBA League Pass",
    nationalTv: [],
    nationalOtt: [],
    homeTv: [],
    awayTv: ["WPLG Local 10"],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 1",
  },
  {
    id: "nets-at-cavaliers-2026-10-24",
    gameId: "0022600105",
    gameCode: "20261024/BKNCLE",
    homeTeamSlug: "cavaliers",
    awayTeamSlug: "nets",
    date: "2026-10-24T23:30:00Z",
    status: "scheduled",
    arena: "Rocket Arena",
    arenaCity: "Cleveland",
    arenaState: "OH",
    broadcast: "NBA League Pass",
    nationalTv: [],
    nationalOtt: [],
    homeTv: [],
    awayTv: ["DAZN (YES)"],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 1",
  },
  {
    id: "bucks-at-76ers-2026-10-24",
    gameId: "0022600106",
    gameCode: "20261024/MILPHI",
    homeTeamSlug: "76ers",
    awayTeamSlug: "bucks",
    date: "2026-10-24T23:30:00Z",
    status: "scheduled",
    arena: "Xfinity Mobile Arena",
    arenaCity: "Philadelphia",
    arenaState: "PA",
    broadcast: "NBA TV",
    nationalTv: ["NBA TV"],
    nationalOtt: [],
    homeTv: [],
    awayTv: [],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 1",
  },
  {
    id: "rockets-at-hawks-2026-10-25",
    gameId: "0022600107",
    gameCode: "20261024/HOUATL",
    homeTeamSlug: "hawks",
    awayTeamSlug: "rockets",
    date: "2026-10-25T00:00:00Z",
    status: "scheduled",
    arena: "State Farm Arena",
    arenaCity: "Atlanta",
    arenaState: "GA",
    broadcast: "NBA League Pass",
    nationalTv: [],
    nationalOtt: [],
    homeTv: [],
    awayTv: [],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 1",
  },
  {
    id: "wizards-at-bulls-2026-10-25",
    gameId: "0022600108",
    gameCode: "20261024/WASCHI",
    homeTeamSlug: "bulls",
    awayTeamSlug: "wizards",
    date: "2026-10-25T00:00:00Z",
    status: "scheduled",
    arena: "United Center",
    arenaCity: "Chicago",
    arenaState: "IL",
    broadcast: "NBA League Pass",
    nationalTv: [],
    nationalOtt: [],
    homeTv: ["Chicago Sports Network"],
    awayTv: [],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 1",
  },
  {
    id: "spurs-at-mavericks-2026-10-25",
    gameId: "0022600109",
    gameCode: "20261024/SASDAL",
    homeTeamSlug: "mavericks",
    awayTeamSlug: "spurs",
    date: "2026-10-25T00:00:00Z",
    status: "scheduled",
    arena: "American Airlines Center",
    arenaCity: "Dallas",
    arenaState: "TX",
    broadcast: "NBA League Pass",
    nationalTv: [],
    nationalOtt: [],
    homeTv: [],
    awayTv: [],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 1",
  },
  {
    id: "pelicans-at-nuggets-2026-10-25",
    gameId: "0022600110",
    gameCode: "20261024/NOPDEN",
    homeTeamSlug: "nuggets",
    awayTeamSlug: "pelicans",
    date: "2026-10-25T01:00:00Z",
    status: "scheduled",
    arena: "Ball Arena",
    arenaCity: "Denver",
    arenaState: "CO",
    broadcast: "NBA League Pass",
    nationalTv: [],
    nationalOtt: [],
    homeTv: ["ALT/ALT+/KTVD"],
    awayTv: [],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 1",
  },
  {
    id: "warriors-at-suns-2026-10-25",
    gameId: "0022600111",
    gameCode: "20261024/GSWPHX",
    homeTeamSlug: "suns",
    awayTeamSlug: "warriors",
    date: "2026-10-25T02:00:00Z",
    status: "scheduled",
    arena: "Mortgage Matchup Center",
    arenaCity: "Phoenix",
    arenaState: "AZ",
    broadcast: "NBA TV",
    nationalTv: ["NBA TV"],
    nationalOtt: [],
    homeTv: ["KPHE/KPHO/AZFS App"],
    awayTv: ["NBCSBA"],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 1",
  },
  {
    id: "lakers-at-jazz-2026-10-25",
    gameId: "0022600112",
    gameCode: "20261025/LALUTA",
    homeTeamSlug: "jazz",
    awayTeamSlug: "lakers",
    date: "2026-10-25T21:00:00Z",
    status: "scheduled",
    arena: "Delta Center",
    arenaCity: "Salt Lake City",
    arenaState: "UT",
    broadcast: "NBA League Pass",
    nationalTv: [],
    nationalOtt: [],
    homeTv: [],
    awayTv: ["Spectrum SportsNet"],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 1",
  },
  {
    id: "pacers-at-nets-2026-10-25",
    gameId: "0022600113",
    gameCode: "20261025/INDBKN",
    homeTeamSlug: "nets",
    awayTeamSlug: "pacers",
    date: "2026-10-25T22:00:00Z",
    status: "scheduled",
    arena: "Barclays Center",
    arenaCity: "Brooklyn",
    arenaState: "NY",
    broadcast: "NBA League Pass",
    nationalTv: [],
    nationalOtt: [],
    homeTv: ["DAZN (YES)"],
    awayTv: [],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 1",
  },
  {
    id: "magic-at-knicks-2026-10-25",
    gameId: "0022600114",
    gameCode: "20261025/ORLNYK",
    homeTeamSlug: "knicks",
    awayTeamSlug: "magic",
    date: "2026-10-25T23:00:00Z",
    status: "scheduled",
    arena: "Madison Square Garden",
    arenaCity: "New York",
    arenaState: "NY",
    broadcast: "NBA League Pass",
    nationalTv: [],
    nationalOtt: [],
    homeTv: [],
    awayTv: [],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 1",
  },
  {
    id: "raptors-at-timberwolves-2026-10-25",
    gameId: "0022600115",
    gameCode: "20261025/TORMIN",
    homeTeamSlug: "timberwolves",
    awayTeamSlug: "raptors",
    date: "2026-10-25T23:00:00Z",
    status: "scheduled",
    arena: "Target Center",
    arenaCity: "Minneapolis",
    arenaState: "MN",
    broadcast: "NBA TV",
    nationalTv: ["NBA TV"],
    nationalOtt: [],
    homeTv: [],
    awayTv: [],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 1",
  },
  {
    id: "clippers-at-thunder-2026-10-25",
    gameId: "0022600116",
    gameCode: "20261025/LACOKC",
    homeTeamSlug: "thunder",
    awayTeamSlug: "clippers",
    date: "2026-10-25T23:00:00Z",
    status: "scheduled",
    arena: "Paycom Center",
    arenaCity: "Oklahoma City",
    arenaState: "OK",
    broadcast: "NBA League Pass",
    nationalTv: [],
    nationalOtt: [],
    homeTv: ["KSBI OKC"],
    awayTv: [],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 1",
  },
  {
    id: "pistons-at-76ers-2026-10-25",
    gameId: "0022600117",
    gameCode: "20261025/DETPHI",
    homeTeamSlug: "76ers",
    awayTeamSlug: "pistons",
    date: "2026-10-25T23:30:00Z",
    status: "scheduled",
    arena: "Xfinity Mobile Arena",
    arenaCity: "Philadelphia",
    arenaState: "PA",
    broadcast: "NBA League Pass",
    nationalTv: [],
    nationalOtt: [],
    homeTv: [],
    awayTv: [],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 1",
  },
  {
    id: "grizzlies-at-kings-2026-10-26",
    gameId: "0022600118",
    gameCode: "20261025/MEMSAC",
    homeTeamSlug: "kings",
    awayTeamSlug: "grizzlies",
    date: "2026-10-26T01:00:00Z",
    status: "scheduled",
    arena: "Golden 1 Center",
    arenaCity: "Sacramento",
    arenaState: "CA",
    broadcast: "NBA League Pass",
    nationalTv: [],
    nationalOtt: [],
    homeTv: ["NBCSCA"],
    awayTv: [],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 1",
  },
  {
    id: "wizards-at-hornets-2026-10-26",
    gameId: "0022600119",
    gameCode: "20261026/WASCHA",
    homeTeamSlug: "hornets",
    awayTeamSlug: "wizards",
    date: "2026-10-26T23:00:00Z",
    status: "scheduled",
    arena: "Spectrum Center",
    arenaCity: "Charlotte",
    arenaState: "NC",
    broadcast: "NBA League Pass",
    nationalTv: [],
    nationalOtt: [],
    homeTv: [],
    awayTv: [],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 2",
  },
  {
    id: "timberwolves-at-cavaliers-2026-10-26",
    gameId: "0022600120",
    gameCode: "20261026/MINCLE",
    homeTeamSlug: "cavaliers",
    awayTeamSlug: "timberwolves",
    date: "2026-10-26T23:00:00Z",
    status: "scheduled",
    arena: "Rocket Arena",
    arenaCity: "Cleveland",
    arenaState: "OH",
    broadcast: "NBA League Pass",
    nationalTv: [],
    nationalOtt: [],
    homeTv: [],
    awayTv: [],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 2",
  },
  {
    id: "bulls-at-celtics-2026-10-26",
    gameId: "0022600121",
    gameCode: "20261026/CHIBOS",
    homeTeamSlug: "celtics",
    awayTeamSlug: "bulls",
    date: "2026-10-26T23:30:00Z",
    status: "scheduled",
    arena: "TD Garden",
    arenaCity: "Boston",
    arenaState: "MA",
    broadcast: "NBA League Pass",
    nationalTv: [],
    nationalOtt: [],
    homeTv: ["NBC SPORTS BOSTON"],
    awayTv: ["Chicago Sports Network"],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 2",
  },
  {
    id: "mavericks-at-heat-2026-10-26",
    gameId: "0022600122",
    gameCode: "20261026/DALMIA",
    homeTeamSlug: "heat",
    awayTeamSlug: "mavericks",
    date: "2026-10-26T23:30:00Z",
    status: "scheduled",
    arena: "Kaseya Center",
    arenaCity: "Miami",
    arenaState: "FL",
    broadcast: "NBA TV",
    nationalTv: ["NBA TV"],
    nationalOtt: [],
    homeTv: ["WPLG Local 10"],
    awayTv: [],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 2",
  },
  {
    id: "pacers-at-bucks-2026-10-27",
    gameId: "0022600123",
    gameCode: "20261026/INDMIL",
    homeTeamSlug: "bucks",
    awayTeamSlug: "pacers",
    date: "2026-10-27T00:00:00Z",
    status: "scheduled",
    arena: "Fiserv Forum",
    arenaCity: "Milwaukee",
    arenaState: "WI",
    broadcast: "NBA League Pass",
    nationalTv: [],
    nationalOtt: [],
    homeTv: [],
    awayTv: [],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 2",
  },
  {
    id: "suns-at-thunder-2026-10-27",
    gameId: "0022600124",
    gameCode: "20261026/PHXOKC",
    homeTeamSlug: "thunder",
    awayTeamSlug: "suns",
    date: "2026-10-27T00:00:00Z",
    status: "scheduled",
    arena: "Paycom Center",
    arenaCity: "Oklahoma City",
    arenaState: "OK",
    broadcast: "NBA League Pass",
    nationalTv: [],
    nationalOtt: [],
    homeTv: ["KSBI OKC"],
    awayTv: ["KTVK/KPHE/AZFS App"],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 2",
  },
  {
    id: "hawks-at-rockets-2026-10-27",
    gameId: "0022600125",
    gameCode: "20261026/ATLHOU",
    homeTeamSlug: "rockets",
    awayTeamSlug: "hawks",
    date: "2026-10-27T00:30:00Z",
    status: "scheduled",
    arena: "Toyota Center",
    arenaCity: "Houston",
    arenaState: "TX",
    broadcast: "NBA League Pass",
    nationalTv: [],
    nationalOtt: [],
    homeTv: [],
    awayTv: [],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 2",
  },
  {
    id: "grizzlies-at-jazz-2026-10-27",
    gameId: "0022600126",
    gameCode: "20261026/MEMUTA",
    homeTeamSlug: "jazz",
    awayTeamSlug: "grizzlies",
    date: "2026-10-27T01:00:00Z",
    status: "scheduled",
    arena: "Delta Center",
    arenaCity: "Salt Lake City",
    arenaState: "UT",
    broadcast: "NBA League Pass",
    nationalTv: [],
    nationalOtt: [],
    homeTv: [],
    awayTv: [],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 2",
  },
  {
    id: "warriors-at-nuggets-2026-10-27",
    gameId: "0022600127",
    gameCode: "20261026/GSWDEN",
    homeTeamSlug: "nuggets",
    awayTeamSlug: "warriors",
    date: "2026-10-27T02:00:00Z",
    status: "scheduled",
    arena: "Ball Arena",
    arenaCity: "Denver",
    arenaState: "CO",
    broadcast: "NBC Sports Network / Peacock",
    nationalTv: ["NBC Sports Network","Peacock"],
    nationalOtt: [],
    homeTv: ["Altitude/Altitude+"],
    awayTv: [],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 2",
  },
  {
    id: "nets-at-celtics-2026-10-27",
    gameId: "0022600128",
    gameCode: "20261027/BKNBOS",
    homeTeamSlug: "celtics",
    awayTeamSlug: "nets",
    date: "2026-10-27T23:30:00Z",
    status: "scheduled",
    arena: "TD Garden",
    arenaCity: "Boston",
    arenaState: "MA",
    broadcast: "NBA League Pass",
    nationalTv: [],
    nationalOtt: [],
    homeTv: ["NBC SPORTS BOSTON"],
    awayTv: ["DAZN (YES)"],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 2",
  },
  {
    id: "pistons-at-knicks-2026-10-28",
    gameId: "0022600129",
    gameCode: "20261027/DETNYK",
    homeTeamSlug: "knicks",
    awayTeamSlug: "pistons",
    date: "2026-10-28T00:00:00Z",
    status: "scheduled",
    arena: "Madison Square Garden",
    arenaCity: "New York",
    arenaState: "NY",
    broadcast: "NBC / Peacock",
    nationalTv: ["NBC","Peacock"],
    nationalOtt: [],
    homeTv: [],
    awayTv: [],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 2",
  },
  {
    id: "kings-at-spurs-2026-10-28",
    gameId: "0022600130",
    gameCode: "20261027/SACSAS",
    homeTeamSlug: "spurs",
    awayTeamSlug: "kings",
    date: "2026-10-28T00:00:00Z",
    status: "scheduled",
    arena: "Frost Bank Center",
    arenaCity: "San Antonio",
    arenaState: "TX",
    broadcast: "NBA League Pass",
    nationalTv: [],
    nationalOtt: [],
    homeTv: [],
    awayTv: ["NBCSCA"],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 2",
  },
  {
    id: "blazers-at-lakers-2026-10-28",
    gameId: "0022600131",
    gameCode: "20261027/PORLAL",
    homeTeamSlug: "lakers",
    awayTeamSlug: "blazers",
    date: "2026-10-28T03:00:00Z",
    status: "scheduled",
    arena: "Crypto.com Arena",
    arenaCity: "Los Angeles",
    arenaState: "CA",
    broadcast: "NBC / Peacock",
    nationalTv: ["NBC","Peacock"],
    nationalOtt: [],
    homeTv: ["Spectrum SportsNet"],
    awayTv: [],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 2",
  },
  {
    id: "heat-at-hawks-2026-10-28",
    gameId: "0022600132",
    gameCode: "20261028/MIAATL",
    homeTeamSlug: "hawks",
    awayTeamSlug: "heat",
    date: "2026-10-28T23:00:00Z",
    status: "scheduled",
    arena: "State Farm Arena",
    arenaCity: "Atlanta",
    arenaState: "GA",
    broadcast: "NBA League Pass",
    nationalTv: [],
    nationalOtt: [],
    homeTv: [],
    awayTv: ["WPLG Local 10"],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 2",
  },
  {
    id: "wizards-at-cavaliers-2026-10-28",
    gameId: "0022600133",
    gameCode: "20261028/WASCLE",
    homeTeamSlug: "cavaliers",
    awayTeamSlug: "wizards",
    date: "2026-10-28T23:00:00Z",
    status: "scheduled",
    arena: "Rocket Arena",
    arenaCity: "Cleveland",
    arenaState: "OH",
    broadcast: "NBA League Pass",
    nationalTv: [],
    nationalOtt: [],
    homeTv: [],
    awayTv: [],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 2",
  },
  {
    id: "hornets-at-pistons-2026-10-28",
    gameId: "0022600134",
    gameCode: "20261028/CHADET",
    homeTeamSlug: "pistons",
    awayTeamSlug: "hornets",
    date: "2026-10-28T23:00:00Z",
    status: "scheduled",
    arena: "Little Caesars Arena",
    arenaCity: "Detroit",
    arenaState: "MI",
    broadcast: "NBA League Pass",
    nationalTv: [],
    nationalOtt: [],
    homeTv: [],
    awayTv: [],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 2",
  },
  {
    id: "76ers-at-pacers-2026-10-28",
    gameId: "0022600135",
    gameCode: "20261028/PHIIND",
    homeTeamSlug: "pacers",
    awayTeamSlug: "76ers",
    date: "2026-10-28T23:00:00Z",
    status: "scheduled",
    arena: "Gainbridge Fieldhouse",
    arenaCity: "Indianapolis",
    arenaState: "IN",
    broadcast: "ESPN",
    nationalTv: ["ESPN"],
    nationalOtt: [],
    homeTv: [],
    awayTv: [],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 2",
  },
  {
    id: "magic-at-raptors-2026-10-28",
    gameId: "0022600136",
    gameCode: "20261028/ORLTOR",
    homeTeamSlug: "raptors",
    awayTeamSlug: "magic",
    date: "2026-10-28T23:30:00Z",
    status: "scheduled",
    arena: "Scotiabank Arena",
    arenaCity: "Toronto",
    arenaState: "ON",
    broadcast: "NBA League Pass",
    nationalTv: [],
    nationalOtt: [],
    homeTv: [],
    awayTv: [],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 2",
  },
  {
    id: "knicks-at-bulls-2026-10-29",
    gameId: "0022600137",
    gameCode: "20261028/NYKCHI",
    homeTeamSlug: "bulls",
    awayTeamSlug: "knicks",
    date: "2026-10-29T00:00:00Z",
    status: "scheduled",
    arena: "United Center",
    arenaCity: "Chicago",
    arenaState: "IL",
    broadcast: "NBA League Pass",
    nationalTv: [],
    nationalOtt: [],
    homeTv: ["Chicago Sports Network"],
    awayTv: [],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 2",
  },
  {
    id: "rockets-at-bucks-2026-10-29",
    gameId: "0022600138",
    gameCode: "20261028/HOUMIL",
    homeTeamSlug: "bucks",
    awayTeamSlug: "rockets",
    date: "2026-10-29T00:00:00Z",
    status: "scheduled",
    arena: "Fiserv Forum",
    arenaCity: "Milwaukee",
    arenaState: "WI",
    broadcast: "NBA League Pass",
    nationalTv: [],
    nationalOtt: [],
    homeTv: [],
    awayTv: [],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 2",
  },
  {
    id: "warriors-at-timberwolves-2026-10-29",
    gameId: "0022600139",
    gameCode: "20261028/GSWMIN",
    homeTeamSlug: "timberwolves",
    awayTeamSlug: "warriors",
    date: "2026-10-29T00:00:00Z",
    status: "scheduled",
    arena: "Target Center",
    arenaCity: "Minneapolis",
    arenaState: "MN",
    broadcast: "NBA League Pass",
    nationalTv: [],
    nationalOtt: [],
    homeTv: [],
    awayTv: ["NBCSBA"],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 2",
  },
  {
    id: "nuggets-at-pelicans-2026-10-29",
    gameId: "0022600140",
    gameCode: "20261028/DENNOP",
    homeTeamSlug: "pelicans",
    awayTeamSlug: "nuggets",
    date: "2026-10-29T00:00:00Z",
    status: "scheduled",
    arena: "Smoothie King Center",
    arenaCity: "New Orleans",
    arenaState: "LA",
    broadcast: "NBA League Pass",
    nationalTv: [],
    nationalOtt: [],
    homeTv: [],
    awayTv: ["ALT2/ALT+/KTVD"],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 2",
  },
  {
    id: "spurs-at-jazz-2026-10-29",
    gameId: "0022600141",
    gameCode: "20261028/SASUTA",
    homeTeamSlug: "jazz",
    awayTeamSlug: "spurs",
    date: "2026-10-29T01:00:00Z",
    status: "scheduled",
    arena: "Delta Center",
    arenaCity: "Salt Lake City",
    arenaState: "UT",
    broadcast: "NBA League Pass",
    nationalTv: [],
    nationalOtt: [],
    homeTv: [],
    awayTv: [],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 2",
  },
  {
    id: "thunder-at-mavericks-2026-10-29",
    gameId: "0022600142",
    gameCode: "20261028/OKCDAL",
    homeTeamSlug: "mavericks",
    awayTeamSlug: "thunder",
    date: "2026-10-29T01:30:00Z",
    status: "scheduled",
    arena: "American Airlines Center",
    arenaCity: "Dallas",
    arenaState: "TX",
    broadcast: "ESPN",
    nationalTv: ["ESPN"],
    nationalOtt: [],
    homeTv: [],
    awayTv: ["KSBI OKC"],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 2",
  },
  {
    id: "lakers-at-clippers-2026-10-29",
    gameId: "0022600143",
    gameCode: "20261028/LALLAC",
    homeTeamSlug: "clippers",
    awayTeamSlug: "lakers",
    date: "2026-10-29T02:30:00Z",
    status: "scheduled",
    arena: "Intuit Dome",
    arenaCity: "Inglewood",
    arenaState: "CA",
    broadcast: "NBA League Pass",
    nationalTv: [],
    nationalOtt: [],
    homeTv: [],
    awayTv: ["Spectrum SportsNet"],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 2",
  },
  {
    id: "cavaliers-at-hawks-2026-10-29",
    gameId: "0022600144",
    gameCode: "20261029/CLEATL",
    homeTeamSlug: "hawks",
    awayTeamSlug: "cavaliers",
    date: "2026-10-29T23:00:00Z",
    status: "scheduled",
    arena: "State Farm Arena",
    arenaCity: "Atlanta",
    arenaState: "GA",
    broadcast: "NBA TV",
    nationalTv: ["NBA TV"],
    nationalOtt: [],
    homeTv: [],
    awayTv: [],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 2",
  },
  {
    id: "kings-at-pelicans-2026-10-30",
    gameId: "0022600145",
    gameCode: "20261029/SACNOP",
    homeTeamSlug: "pelicans",
    awayTeamSlug: "kings",
    date: "2026-10-30T00:00:00Z",
    status: "scheduled",
    arena: "Smoothie King Center",
    arenaCity: "New Orleans",
    arenaState: "LA",
    broadcast: "NBA League Pass",
    nationalTv: [],
    nationalOtt: [],
    homeTv: [],
    awayTv: ["NBCSCA"],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 2",
  },
  {
    id: "grizzlies-at-blazers-2026-10-30",
    gameId: "0022600146",
    gameCode: "20261029/MEMPOR",
    homeTeamSlug: "blazers",
    awayTeamSlug: "grizzlies",
    date: "2026-10-30T02:00:00Z",
    status: "scheduled",
    arena: "Moda Center",
    arenaCity: "Portland",
    arenaState: "OR",
    broadcast: "NBA League Pass",
    nationalTv: [],
    nationalOtt: [],
    homeTv: ["KUNP"],
    awayTv: [],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 2",
  },
  {
    id: "hornets-at-wizards-2026-10-30",
    gameId: "0022600015",
    gameCode: "20261030/CHAWAS",
    homeTeamSlug: "wizards",
    awayTeamSlug: "hornets",
    date: "2026-10-30T23:00:00Z",
    status: "scheduled",
    arena: "Capital One Arena",
    arenaCity: "Washington",
    arenaState: "DC",
    broadcast: "NBA League Pass",
    nationalTv: [],
    nationalOtt: [],
    homeTv: [],
    awayTv: [],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "Emirates NBA Cup — East Group C",
    week: "Week 2",
  },
  {
    id: "bulls-at-celtics-2026-10-30",
    gameId: "0022600016",
    gameCode: "20261030/CHIBOS",
    homeTeamSlug: "celtics",
    awayTeamSlug: "bulls",
    date: "2026-10-30T23:30:00Z",
    status: "scheduled",
    arena: "TD Garden",
    arenaCity: "Boston",
    arenaState: "MA",
    broadcast: "NBA League Pass",
    nationalTv: [],
    nationalOtt: [],
    homeTv: ["NBC SPORTS BOSTON"],
    awayTv: ["Chicago Sports Network"],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "Emirates NBA Cup — East Group C",
    week: "Week 2",
  },
  {
    id: "pistons-at-nets-2026-10-30",
    gameId: "0022600017",
    gameCode: "20261030/DETBKN",
    homeTeamSlug: "nets",
    awayTeamSlug: "pistons",
    date: "2026-10-30T23:30:00Z",
    status: "scheduled",
    arena: "Barclays Center",
    arenaCity: "Brooklyn",
    arenaState: "NY",
    broadcast: "NBA League Pass",
    nationalTv: [],
    nationalOtt: [],
    homeTv: ["DAZN (YES)"],
    awayTv: [],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "Emirates NBA Cup — East Group A",
    week: "Week 2",
  },
  {
    id: "knicks-at-76ers-2026-10-30",
    gameId: "0022600018",
    gameCode: "20261030/NYKPHI",
    homeTeamSlug: "76ers",
    awayTeamSlug: "knicks",
    date: "2026-10-30T23:30:00Z",
    status: "scheduled",
    arena: "Xfinity Mobile Arena",
    arenaCity: "Philadelphia",
    arenaState: "PA",
    broadcast: "Prime Video",
    nationalTv: ["Prime Video"],
    nationalOtt: [],
    homeTv: [],
    awayTv: [],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "Emirates NBA Cup — East Group B",
    week: "Week 2",
  },
  {
    id: "magic-at-raptors-2026-10-30",
    gameId: "0022600019",
    gameCode: "20261030/ORLTOR",
    homeTeamSlug: "raptors",
    awayTeamSlug: "magic",
    date: "2026-10-30T23:30:00Z",
    status: "scheduled",
    arena: "Scotiabank Arena",
    arenaCity: "Toronto",
    arenaState: "ON",
    broadcast: "NBA League Pass",
    nationalTv: [],
    nationalOtt: [],
    homeTv: [],
    awayTv: [],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "Emirates NBA Cup — East Group A",
    week: "Week 2",
  },
  {
    id: "pacers-at-heat-2026-10-31",
    gameId: "0022600020",
    gameCode: "20261030/INDMIA",
    homeTeamSlug: "heat",
    awayTeamSlug: "pacers",
    date: "2026-10-31T00:00:00Z",
    status: "scheduled",
    arena: "Kaseya Center",
    arenaCity: "Miami",
    arenaState: "FL",
    broadcast: "NBA League Pass",
    nationalTv: [],
    nationalOtt: [],
    homeTv: ["WPLG Local 10"],
    awayTv: [],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "Emirates NBA Cup — East Group B",
    week: "Week 2",
  },
  {
    id: "rockets-at-mavericks-2026-10-31",
    gameId: "0022600021",
    gameCode: "20261030/HOUDAL",
    homeTeamSlug: "mavericks",
    awayTeamSlug: "rockets",
    date: "2026-10-31T00:00:00Z",
    status: "scheduled",
    arena: "American Airlines Center",
    arenaCity: "Dallas",
    arenaState: "TX",
    broadcast: "NBA League Pass",
    nationalTv: [],
    nationalOtt: [],
    homeTv: [],
    awayTv: [],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "Emirates NBA Cup — West Group A",
    week: "Week 2",
  },
  {
    id: "clippers-at-timberwolves-2026-10-31",
    gameId: "0022600022",
    gameCode: "20261030/LACMIN",
    homeTeamSlug: "timberwolves",
    awayTeamSlug: "clippers",
    date: "2026-10-31T00:00:00Z",
    status: "scheduled",
    arena: "Target Center",
    arenaCity: "Minneapolis",
    arenaState: "MN",
    broadcast: "NBA League Pass",
    nationalTv: [],
    nationalOtt: [],
    homeTv: [],
    awayTv: [],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "Emirates NBA Cup — West Group B",
    week: "Week 2",
  },
  {
    id: "lakers-at-warriors-2026-10-31",
    gameId: "0022600023",
    gameCode: "20261030/LALGSW",
    homeTeamSlug: "warriors",
    awayTeamSlug: "lakers",
    date: "2026-10-31T02:00:00Z",
    status: "scheduled",
    arena: "Chase Center",
    arenaCity: "San Francisco",
    arenaState: "CA",
    broadcast: "Prime Video",
    nationalTv: ["Prime Video"],
    nationalOtt: [],
    homeTv: [],
    awayTv: [],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "Emirates NBA Cup — West Group C",
    week: "Week 2",
  },
  {
    id: "nuggets-at-suns-2026-10-31",
    gameId: "0022600024",
    gameCode: "20261030/DENPHX",
    homeTeamSlug: "suns",
    awayTeamSlug: "nuggets",
    date: "2026-10-31T02:00:00Z",
    status: "scheduled",
    arena: "Mortgage Matchup Center",
    arenaCity: "Phoenix",
    arenaState: "AZ",
    broadcast: "NBA League Pass",
    nationalTv: [],
    nationalOtt: [],
    homeTv: ["KTVK/KPHE/AZFS App"],
    awayTv: ["Altitude/Altitude+"],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "Emirates NBA Cup — West Group A",
    week: "Week 2",
  },
  {
    id: "blazers-at-jazz-2026-10-31",
    gameId: "0022600147",
    gameCode: "20261031/PORUTA",
    homeTeamSlug: "jazz",
    awayTeamSlug: "blazers",
    date: "2026-10-31T19:00:00Z",
    status: "scheduled",
    arena: "Delta Center",
    arenaCity: "Salt Lake City",
    arenaState: "UT",
    broadcast: "NBA League Pass",
    nationalTv: [],
    nationalOtt: [],
    homeTv: [],
    awayTv: ["KUNP"],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 2",
  },
  {
    id: "76ers-at-hornets-2026-10-31",
    gameId: "0022600148",
    gameCode: "20261031/PHICHA",
    homeTeamSlug: "hornets",
    awayTeamSlug: "76ers",
    date: "2026-10-31T22:00:00Z",
    status: "scheduled",
    arena: "Spectrum Center",
    arenaCity: "Charlotte",
    arenaState: "NC",
    broadcast: "NBA TV",
    nationalTv: ["NBA TV"],
    nationalOtt: [],
    homeTv: [],
    awayTv: [],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 2",
  },
  {
    id: "hawks-at-pelicans-2026-10-31",
    gameId: "0022600149",
    gameCode: "20261031/ATLNOP",
    homeTeamSlug: "pelicans",
    awayTeamSlug: "hawks",
    date: "2026-10-31T23:00:00Z",
    status: "scheduled",
    arena: "Smoothie King Center",
    arenaCity: "New Orleans",
    arenaState: "LA",
    broadcast: "NBA League Pass",
    nationalTv: [],
    nationalOtt: [],
    homeTv: [],
    awayTv: [],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 2",
  },
  {
    id: "kings-at-grizzlies-2026-11-01",
    gameId: "0022600150",
    gameCode: "20261031/SACMEM",
    homeTeamSlug: "grizzlies",
    awayTeamSlug: "kings",
    date: "2026-11-01T00:00:00Z",
    status: "scheduled",
    arena: "FedExForum",
    arenaCity: "Memphis",
    arenaState: "TN",
    broadcast: "NBA League Pass",
    nationalTv: [],
    nationalOtt: [],
    homeTv: [],
    awayTv: ["NBCSCA"],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 2",
  },
  {
    id: "cavaliers-at-bucks-2026-11-01",
    gameId: "0022600151",
    gameCode: "20261031/CLEMIL",
    homeTeamSlug: "bucks",
    awayTeamSlug: "cavaliers",
    date: "2026-11-01T00:00:00Z",
    status: "scheduled",
    arena: "Fiserv Forum",
    arenaCity: "Milwaukee",
    arenaState: "WI",
    broadcast: "NBA League Pass",
    nationalTv: [],
    nationalOtt: [],
    homeTv: [],
    awayTv: [],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 2",
  },
  {
    id: "timberwolves-at-spurs-2026-11-01",
    gameId: "0022600152",
    gameCode: "20261031/MINSAS",
    homeTeamSlug: "spurs",
    awayTeamSlug: "timberwolves",
    date: "2026-11-01T00:00:00Z",
    status: "scheduled",
    arena: "Frost Bank Center",
    arenaCity: "San Antonio",
    arenaState: "TX",
    broadcast: "NBA League Pass",
    nationalTv: [],
    nationalOtt: [],
    homeTv: [],
    awayTv: [],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 2",
  },
  {
    id: "thunder-at-rockets-2026-11-01",
    gameId: "0022600153",
    gameCode: "20261031/OKCHOU",
    homeTeamSlug: "rockets",
    awayTeamSlug: "thunder",
    date: "2026-11-01T00:30:00Z",
    status: "scheduled",
    arena: "Toyota Center",
    arenaCity: "Houston",
    arenaState: "TX",
    broadcast: "NBA TV",
    nationalTv: ["NBA TV"],
    nationalOtt: [],
    homeTv: [],
    awayTv: ["KSBI/KWTV OKC"],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 2",
  },
  {
    id: "celtics-at-magic-2026-11-01",
    gameId: "0022600154",
    gameCode: "20261101/BOSORL",
    homeTeamSlug: "magic",
    awayTeamSlug: "celtics",
    date: "2026-11-01T20:30:00Z",
    status: "scheduled",
    arena: "Kia Center",
    arenaCity: "Orlando",
    arenaState: "FL",
    broadcast: "NBA League Pass",
    nationalTv: [],
    nationalOtt: [],
    homeTv: [],
    awayTv: ["NBC SPORTS BOSTON"],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 2",
  },
  {
    id: "nets-at-pacers-2026-11-01",
    gameId: "0022600155",
    gameCode: "20261101/BKNIND",
    homeTeamSlug: "pacers",
    awayTeamSlug: "nets",
    date: "2026-11-01T22:00:00Z",
    status: "scheduled",
    arena: "Gainbridge Fieldhouse",
    arenaCity: "Indianapolis",
    arenaState: "IN",
    broadcast: "NBA League Pass",
    nationalTv: [],
    nationalOtt: [],
    homeTv: [],
    awayTv: ["DAZN (YES)"],
    radio: ["SiriusXM"],
    homeRecord: "0-0",
    awayRecord: "0-0",
    label: "",
    week: "Week 2",
  },
];
